# Daily data processing

This notebook is part of a toolset to analyse and visualise data on the COVID-19 epidimic and will be run once a day.<br>
Though this can only be done locally on my machine, the data will be saved in ../data/ in this repository.

We will use the data downloaded and extracted, by the other notebook in this directory, we will now mold this data into a few sets that we will be working with. The content of these datasets will be explained as we create them, though here is as overview.

#### Outbreak spread:
    - Total cases, deaths
    - Weekly cases, deaths
    
#### Country impact:
    - Prevalence
    - Daily, weekly incidence
    
#### Other:
    - Mortality
    - Threshold dates
    - Global data
    - Continental data

## Data import

Before we can do anything we'll have to load up the three datasets created by the other worksheet, setting the index appropriatly. Note that when saving the sets as .csv files, pandas saves the dates as strings. So to be able to compare them as dates, before we set them as the indexes, we need to tell pandas to translate that column to datetimes.

To make the processing easier to read we will also already make two lists containing all the available dates and countries, as well as getting the last available date.

In [1]:
import pandas as pd
import datetime

df_cases_daily = pd.read_csv('../data/cases_daily.csv')
df_cases_daily['Date'] = df_cases_daily['Date'].astype('datetime64[ns]')
df_cases_daily = df_cases_daily.set_index('Date')

df_deaths_daily = pd.read_csv('../data/deaths_daily.csv')
df_deaths_daily['Date'] = df_deaths_daily['Date'].astype('datetime64[ns]') 
df_deaths_daily = df_deaths_daily.set_index('Date')

df_populations = pd.read_csv('../data/populations_2018.csv').set_index('Countries')

dates_all = df_cases_daily.index
countries_all = df_cases_daily.columns

latest_date = dates_all[-1]

## Total

The first datasets we willl create will be the ones containing the total amount of cases and deaths per day. This is easilly done by looping through all the dates for a particular country and adding all the values to their respective counter.

Note that the structure of these datasets will be the same as the ones for daily cases and deaths, the same countries as collumns and every day as index. So we can just copy that dataset and overwrite it instead of having to make new dictionaries to create our dataframe with.

In [2]:
df_cases_total = df_cases_daily.copy()
df_deaths_total = df_deaths_daily.copy()

for country in countries_all:
    cases = 0
    deaths = 0
    
    for date in dates_all:
        cases += df_cases_daily.at[date, country]
        deaths += df_deaths_daily.at[date, country]
        
        df_cases_total.at[date, country] = cases
        df_deaths_total.at[date, country] = deaths
        
display(df_cases_total)
display(df_deaths_total)

df_cases_total.to_csv('../data/cases_total.csv')
df_deaths_total.to_csv('../data/deaths_total.csv')

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2019-12-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,166,243,584,376,7,2,7,966,532,55,...,25150,19,30,189618,338,173,135,229,35,8
2020-04-02,192,259,847,390,8,2,7,1133,571,55,...,29474,20,30,216721,338,187,143,235,36,8
2020-04-03,235,277,847,428,8,3,9,1133,663,60,...,33718,21,33,245540,369,190,144,239,39,8
2020-04-04,235,304,986,439,8,3,15,1265,736,62,...,38168,21,40,277965,386,227,144,239,39,9
2020-04-05,270,333,1300,466,10,3,15,1451,770,64,...,41903,21,40,312237,400,266,144,240,39,9

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2019-12-31,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-01,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-02,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-03,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020-01-04,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,4,15,35,12,2,0,0,24,3,0,...,1789,1,0,4079,1,2,3,0,0,1
2020-04-02,4,15,58,14,2,0,0,31,3,0,...,2532,1,0,5138,2,2,3,0,0,1
2020-04-03,4,16,58,15,2,0,0,34,4,0,...,2921,1,0,6053,4,2,3,0,1,1
2020-04-04,4,17,83,16,2,0,0,37,7,0,...,3605,1,0,7157,4,2,3,0,1,1
2020-04-05,5,19,130,17,2,0,0,43,7,0,...,4313,1,0,8501,5,2,5,0,1,1

## Weekly

To create the datasets containing weekly cases and deaths, we will first need to create a list containng the dates starting from the latest date we have and counting back per week till the last date that is still available.

When the list is created we will revert it so the order o the datasets we create will still be from earliest to most recent.

In [3]:
dates_weekly = []

start_date = latest_date
end_date = start_date - datetime.timedelta(days=7)

while end_date > df_cases_daily.index[0]:
    dates_weekly.append(start_date)
    
    start_date = end_date
    end_date = start_date - datetime.timedelta(days=7)

dates_weekly.reverse()

Now that we know which dates we need to look at we can create the datasets. 
This will be done by, per date, taking the sum of the values between that date and a week earlier.

Since the structure will be different from the daily sets, since there will be less entries, it is more readable to create them using dictionaries as we saw in the other Data-Download notebook.

In [4]:
dict_cases_weekly = {'Date': dates_weekly}
dict_deaths_weekly = {'Date': dates_weekly}

for country in countries_all:
    cases_weekly = []
    deaths_weekly = []
    
    for date in dates_weekly:
        end_date = date - datetime.timedelta(days=6)
        
        cases_weekly.append(df_cases_daily.loc[end_date:date, country].sum() / 7)
        deaths_weekly.append(df_deaths_daily.loc[end_date:date, country].sum() / 7)
    
    dict_cases_weekly[country] = cases_weekly
    dict_deaths_weekly[country] = deaths_weekly

df_cases_weekly = pd.DataFrame(dict_cases_weekly).set_index('Date')
df_deaths_weekly = pd.DataFrame(dict_deaths_weekly).set_index('Date')

display(df_cases_weekly)
display(df_deaths_weekly)

df_cases_weekly.to_csv('../data/cases_weekly.csv')
df_deaths_weekly.to_csv('../data/deaths_weekly.csv')

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.285714,0.000000,0.000000,0.000000,0.285714,0.000000,0.000000
2020-02-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.285714,0.000000,0.000000,0.857143,0.000000,0.000000,0.000000,0.714286,0.000000,0.000000
2020-02-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.285714,0.000000,0.000000,0.571429,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
2020-02-16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.714286,0.000000,0.000000,0.428571,0.000000,0.000000,0.000000,0.285714,0.000000,0.000000
2020-02-23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.857143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-03-01,0.142857,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.142857,0.000000,...,2.000000,0.000000,0.000000,4.857143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-03-08,0.428571,0.000000,2.285714,0.142857,0.000000,0.000000,0.000000,1.285714,0.000000,0.000000,...,26.142857,0.000000,0.000000,52.000000,0.000000,0.000000,0.000000,0.714286,0.000000,0.000000
2020-03-15,0.857143,5.428571,2.857143,0.142857,0.000000,0.000000,0.142857,5.142857,2.714286,0.285714,...,133.428571,0.000000,0.000000,359.714286,0.857143,0.000000,1.428571,4.571429,0.000000,0.000000
2020-03-22,2.000000,5.428571,8.142857,12.285714,0.285714,0.000000,0.000000,25.714286,20.000000,0.285714,...,554.000000,0.857143,0.000000,3399.428571,18.428571,4.714286,3.714286,5.857143,0.285714,0.285714
2020-03-29,11.714286,17.285714,45.000000,31.428571,0.285714,0.285714,0.857143,74.285714,37.714286,3.428571,...,1724.428571,1.000000,3.142857,13988.285714,24.142857,14.285714,11.857143,18.428571,3.714286,0.714286
2020-04-05,23.428571,19.428571,127.285714,22.571429,0.857143,0.142857,1.142857,100.857143,49.428571,5.142857,...,3544.857143,1.142857,2.571429,26796.000000,13.714286,19.000000,3.571429,2.428571,1.571429,0.285714

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-12,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-19,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-16,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-23,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.142857,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.142857,0.000000,0.0,...,0.285714,0.000000,0.0,2.285714,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-15,0.000000,0.142857,0.285714,0.000000,0.000000,0.0,0.0,0.142857,0.000000,0.0,...,2.714286,0.000000,0.0,5.714286,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-22,0.000000,0.142857,1.142857,0.000000,0.000000,0.0,0.0,0.285714,0.000000,0.0,...,30.285714,0.000000,0.0,40.428571,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-29,0.428571,1.142857,2.285714,0.571429,0.000000,0.0,0.0,2.142857,0.428571,0.0,...,112.285714,0.142857,0.0,264.428571,0.000000,0.142857,0.142857,0.0,0.000000,0.142857
2020-04-05,0.285714,1.285714,14.857143,1.857143,0.285714,0.0,0.0,3.428571,0.571429,0.0,...,470.571429,0.000000,0.0,901.428571,0.714286,0.142857,0.571429,0.0,0.142857,0.000000

## 3 Day average

In [5]:
dates_3days = []

start_date = latest_date
end_date = start_date - datetime.timedelta(days=3)

while end_date > df_cases_daily.index[0]:
    dates_3days.append(start_date)
    
    start_date = end_date
    end_date = start_date - datetime.timedelta(days=3)

dates_3days.reverse()

dict_cases_3days = {'Date': dates_3days}
dict_deaths_3days = {'Date': dates_3days}

for country in countries_all:
    cases_3days = []
    deaths_3days = []
    
    for date in dates_3days:
        end_date = date - datetime.timedelta(days=2)
        
        cases_3days.append(df_cases_daily.loc[end_date:date, country].sum() / 3)
        deaths_3days.append(df_deaths_daily.loc[end_date:date, country].sum() / 3)
    
    dict_cases_3days[country] = cases_3days
    dict_deaths_3days[country] = deaths_3days

df_cases_3days = pd.DataFrame(dict_cases_3days).set_index('Date')
df_deaths_3days = pd.DataFrame(dict_deaths_3days).set_index('Date')

display(df_cases_3days)
display(df_deaths_3days)

df_cases_3days.to_csv('../data/cases_3days.csv')
df_deaths_3days.to_csv('../data/deaths_3days.csv')

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000
2020-01-27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-01-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-02-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.666667,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.666667,0.000000,0.000000
2020-02-05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
2020-02-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.333333,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
2020-02-11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.666667,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000
2020-02-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.333333,0.000000,0.000000,0.666667,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000
2020-02-17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-02-20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-02-23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,6.666667,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-02-26,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.333333,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-02-29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.666667,0.000000,0.000000,4.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-03-03,0.000000,0.000000,0.666667,0.333333,0.000000,0.000000,0.000000,0.000000,0.333333,0.000000,...,7.333333,0.000000,0.000000,12.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-03-06,0.000000,0.000000,4.666667,0.000000,0.000000,0.000000,0.000000,0.666667,0.000000,0.000000,...,25.000000,0.000000,0.000000,43.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2020-03-09,1.000000,0.666667,1.000000,0.000000,0.000000,0.000000,0.000000,3.333333,0.000000,0.000000,...,52.666667,0.000000,0.000000,107.000000,0.000000,0.000000,0.000000,4.666667,0.000000,0.000000
2020-03-12,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.333333,1.000000,0.000000,...,61.000000,0.000000,0.000000,252.666667,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000
2020-03-15,1.000000,9.000000,5.666667,0.333333,0.000000,0.000000,0.333333,8.666667,5.333333,0.666667,...,228.000000,0.000000,0.000000,546.333333,2.000000,0.000000,3.333333,4.666667,0.000000,0.000000
2020-03-18,4.000000,5.666667,7.666667,4.000000,0.000000,0.000000,0.000000,11.333333,19.333333,0.000000,...,270.000000,0.333333,0.000000,1158.666667,14.666667,5.333333,7.666667,2.666667,0.000000,0.000000
2020-03-21,0.666667,5.000000,11.333333,20.333333,0.000000,0.000000,0.000000,26.333333,19.333333,0.666667,...,677.666667,0.666667,0.000000,4399.000000,20.000000,5.666667,1.000000,8.666667,0.666667,0.333333
2020-03-24,5.333333,10.000000,31.666667,19.333333,0.666667,0.000000,0.000000,47.666667,19.333333,2.666667,...,889.000000,3.000000,5.666667,8939.333333,17.333333,5.333333,16.000000,12.000000,0.333333,0.333333
2020-03-27,11.666667,24.666667,38.666667,30.333333,0.333333,0.666667,2.000000,96.000000,45.000000,5.333333,...,1669.333333,0.333333,0.000000,13183.000000,25.333333,11.333333,7.666667,10.000000,3.666667,0.333333
2020-03-30,13.000000,12.666667,49.666667,36.666667,1.333333,0.000000,0.000000,77.000000,31.666667,7.333333,...,2621.333333,0.333333,4.333333,19011.333333,23.666667,20.666667,4.000000,25.000000,5.000000,1.333333
2020-04-02,26.000000,15.666667,131.000000,18.666667,0.333333,0.000000,0.000000,104.333333,49.000000,1.666667,...,3317.333333,2.000000,0.000000,24565.333333,9.666667,14.000000,8.000000,2.333333,2.333333,0.333333
2020-04-05,26.000000,24.666667,151.000000,25.333333,0.666667,0.333333,2.666667,106.000000,66.333333,3.000000,...,4143.000000,0.333333,3.333333,31838.666667,20.666667,26.333333,0.333333,1.666667,1.000000,0.333333

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-12,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-15,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-18,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-21,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-24,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-27,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-30,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-05,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-11,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-14,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-17,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-20,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-23,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-26,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-02-29,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-03,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,2.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-06,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.333333,0.000000,0.0,2.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.333333,0.000000,0.0,...,0.666667,0.000000,0.0,3.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-12,0.000000,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,1.000000,0.000000,0.0,3.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-15,0.000000,0.000000,0.666667,0.000000,0.000000,0.0,0.0,0.333333,0.000000,0.0,...,5.000000,0.000000,0.0,9.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-18,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,13.000000,0.000000,0.0,17.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-21,0.000000,0.333333,1.666667,0.000000,0.000000,0.0,0.0,0.333333,0.000000,0.0,...,39.000000,0.000000,0.0,50.666667,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-03-24,0.333333,0.666667,2.333333,0.000000,0.000000,0.0,0.0,0.333333,0.000000,0.0,...,52.666667,0.000000,0.0,110.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.333333
2020-03-27,0.000000,0.666667,1.333333,1.000000,0.000000,0.0,0.0,2.666667,0.333333,0.0,...,81.000000,0.000000,0.0,235.333333,0.000000,0.000000,0.333333,0.0,0.000000,0.000000
2020-03-30,1.000000,1.333333,2.666667,1.000000,0.666667,0.0,0.0,2.666667,0.666667,0.0,...,216.666667,0.333333,0.0,404.333333,0.333333,0.333333,0.000000,0.0,0.000000,0.000000
2020-04-02,0.000000,1.666667,9.666667,2.666667,0.000000,0.0,0.0,3.666667,0.000000,0.0,...,434.666667,0.000000,0.0,876.333333,0.333333,0.333333,0.666667,0.0,0.000000,0.000000
2020-04-05,0.333333,1.333333,24.000000,1.000000,0.000000,0.0,0.0,4.000000,1.333333,0.0,...,593.666667,0.000000,0.0,1121.000000,1.000000,0.000000,0.666667,0.0,0.333333,0.000000

## Mortality

Next we will be creating the dataset containing the mortality rates. Again, since the structure doesn't change, we will be copying an existsing dataframe and overwriting it. 

Note that we do need to change the value types for the cells to float since they were read as int when loading the file. Which would cause all values to become 0. As well as the fact that we need to verify that there are any cases, as to not divide by 0.

- mortality = total deaths / total cases

In [6]:
df_mortality = df_deaths_daily.copy().astype('float')

for country in countries_all:
    for date in dates_all:
        if df_cases_total.at[date, country] != 0:
            df_mortality.at[date, country] = df_deaths_total.at[date, country] / df_cases_total.at[date, country]
        else:
            df_mortality.at[date, country] = 0
            
display(df_mortality)
df_mortality.to_csv('../data/mortality.csv')

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2019-12-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-03,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
2020-01-04,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,0.024096,0.061728,0.059932,0.031915,0.285714,0.0,0.0,0.024845,0.005639,0.0,...,0.071133,0.052632,0.0,0.021512,0.002959,0.011561,0.022222,0.0,0.000000,0.125000
2020-04-02,0.020833,0.057915,0.068477,0.035897,0.250000,0.0,0.0,0.027361,0.005254,0.0,...,0.085906,0.050000,0.0,0.023708,0.005917,0.010695,0.020979,0.0,0.000000,0.125000
2020-04-03,0.017021,0.057762,0.068477,0.035047,0.250000,0.0,0.0,0.030009,0.006033,0.0,...,0.086630,0.047619,0.0,0.024652,0.010840,0.010526,0.020833,0.0,0.025641,0.125000
2020-04-04,0.017021,0.055921,0.084178,0.036446,0.250000,0.0,0.0,0.029249,0.009511,0.0,...,0.094451,0.047619,0.0,0.025748,0.010363,0.008811,0.020833,0.0,0.025641,0.111111
2020-04-05,0.018519,0.057057,0.100000,0.036481,0.200000,0.0,0.0,0.029635,0.009091,0.0,...,0.102928,0.047619,0.0,0.027226,0.012500,0.007519,0.034722,0.0,0.025641,0.111111

# Thresholds

To make our lives easier when trying to visualise the data, we're going to create a new datafram, using a dictionary, holding the threshold dates. The reason for this will become apparent in the visualization notebooks. 

When a country hasn't passed a threshold, we will fill in the date of tomorrow as a place holder.
The thresholds are as followed: 
- cases > 100
- deaths > 10

In [7]:
dict_thresholds = {'ind' : ['cases', 'deaths']}

for country in countries_all:
    date_list = df_cases_total.loc[df_cases_total[country] > 100][country].index.tolist()
    if len(date_list) > 0:
        cases_date = date_list[0]
    else:
        cases_date = latest_date + datetime.timedelta(days=1)
    
    date_list = df_deaths_total.loc[df_deaths_total[country] > 10][country].index.tolist()
    if len(date_list) > 0:
        deaths_date = date_list[0]
    else:
        deaths_date = latest_date + datetime.timedelta(days=1)
    
    dict_thresholds[country] = [cases_date, deaths_date]
    
df_thresholds = pd.DataFrame(dict_thresholds).set_index('ind')
display(df_thresholds)
df_thresholds.to_csv('../data/thresholds.csv')

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
ind,,,,,,,,,,,,,,,,,,,,,
cases,2020-03-29,2020-03-25,2020-03-23,2020-03-23,2020-04-06,2020-04-06,2020-04-06,2020-03-20,2020-03-19,2020-04-06,...,2020-03-06,2020-04-06,2020-04-06,2020-03-03,2020-03-21,2020-03-28,2020-03-26,2020-03-23,2020-04-06,2020-04-06
deaths,2020-04-06,2020-03-31,2020-03-23,2020-04-01,2020-04-06,2020-04-06,2020-04-06,2020-03-27,2020-04-06,2020-04-06,...,2020-03-15,2020-04-06,2020-04-06,2020-03-05,2020-04-06,2020-04-06,2020-04-06,2020-04-06,2020-04-06,2020-04-06

## Prevalence & Incidence

Before we continue creating the next datasets I want to clearify why I made the distiction at the top of this notebook between 'Outbreak spread' and 'Country impact'. As this is a distintion that will continue throughout the project.

The daily, weekly and total datasets all contain all absolute number, by which I mean they are not relative to any country metrics, such as population size, density, healthcare, ext. This means that those numbers will be used to track and visualise the intensity of the spread of the outbreak itself in the different countries. With the hopes of finding when which countries are slowing down or containing the outbreak to see if we can look at which measures where taken at those times and if these might be replicated.

On the other side, the datasets that we will now create will consist of numbers that are relative to the population size. Meaning that they represent how heavilly each country is impacted by the outbreak. Which can then be used to see which countries require more aid at this time and later, hopefully, show us general progressions that can be compare to countries where a new outbreak starts. The choice of these metrics was inspired by the WHO (World Health Organization) and are as followed:

- Prevalence = Total cases / Population
- Incidence = New cases / Population

With that out of the way, we can continue.<br>

Note that we verify if we have the population data on the country before we do this, otherwise we would divide by 0. In this case, for now, we will just fill that country's data with 0's. This will cause it to be disregarded in the visualization and analysis, which is not ideal. But this will hopefully be rectified in the future.

In [8]:
df_prevalence = df_cases_daily.copy().astype('float')
df_incidence_daily = df_cases_daily.copy().astype('float')
df_incidence_weekly = df_cases_weekly.copy().astype('float')
df_incidence_3days = df_cases_3days.copy().astype('float')

for country in countries_all:
    ok = (df_populations.at[country, 'populations'] != 0)
    
    for date in dates_all:
        if ok:
            df_prevalence.at[date, country] = df_cases_total.at[date, country] / df_populations.at[country, 'populations']
            df_incidence_daily.at[date, country] = df_cases_daily.at[date, country] / df_populations.at[country, 'populations']
        else: 
            df_prevalence.at[date, country] = 0
            df_incidence_daily.at[date, country] = 0
            
    for date in dates_weekly:
        if ok:
            df_incidence_weekly.at[date, country] = df_cases_weekly.at[date, country] / df_populations.at[country, 'populations']
        else: 
            df_incidence_weekly.at[date, country] = 0
            
    for date in dates_3days:
        if ok:
            df_incidence_3days.at[date, country] = df_cases_3days.at[date, country] / df_populations.at[country, 'populations']
        else: 
            df_incidence_3days.at[date, country] = 0
            
display(df_prevalence)   
display(df_incidence_daily)
display(df_incidence_weekly)
display(df_incidence_3days)

df_prevalence.to_csv('../data/prevalence.csv')
df_incidence_daily.to_csv('../data/incidence_daily.csv')
df_incidence_weekly.to_csv('../data/incidence_weekly.csv')
df_incidence_3days.to_csv('../data/incidence_3days.csv')

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2019-12-31,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
2020-01-01,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
2020-01-02,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
2020-01-03,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
2020-01-04,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,0.000004,0.000085,0.000014,0.004883,2.272007e-07,0.0,0.000073,0.000022,0.000180,0.000520,...,0.000378,3.373679e-07,0.000280,0.000580,0.000098,0.000005,0.000005,0.000002,0.000002,5.540543e-07
2020-04-02,0.000005,0.000090,0.000020,0.005065,2.596580e-07,0.0,0.000073,0.000025,0.000193,0.000520,...,0.000443,3.551241e-07,0.000280,0.000662,0.000098,0.000006,0.000005,0.000002,0.000002,5.540543e-07
2020-04-03,0.000006,0.000097,0.000020,0.005558,2.596580e-07,0.0,0.000093,0.000025,0.000225,0.000567,...,0.000507,3.728803e-07,0.000308,0.000751,0.000107,0.000006,0.000005,0.000003,0.000002,5.540543e-07
2020-04-04,0.000006,0.000106,0.000023,0.005701,2.596580e-07,0.0,0.000156,0.000028,0.000249,0.000586,...,0.000574,3.728803e-07,0.000374,0.000850,0.000112,0.000007,0.000005,0.000003,0.000002,6.233111e-07
2020-04-05,0.000007,0.000116,0.000031,0.006051,3.245725e-07,0.0,0.000156,0.000033,0.000261,0.000605,...,0.000630,3.728803e-07,0.000374,0.000954,0.000116,0.000008,0.000005,0.000003,0.000002,6.233111e-07

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2019-12-31,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-01,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-02,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-03,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-04,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,6.725422e-07,0.000007,0.000002,0.000078,0.000000e+00,0.0,0.000000,0.000000,0.000017,0.000047,...,0.000045,0.000000e+00,0.000000,0.000076,0.000005,7.282570e-07,0.000000e+00,0.000000e+00,0.000000e+00,6.925679e-08
2020-04-02,6.994439e-07,0.000006,0.000006,0.000182,3.245725e-08,0.0,0.000000,0.000004,0.000013,0.000000,...,0.000065,1.775620e-08,0.000000,0.000083,0.000000,4.248166e-07,2.771024e-07,6.280066e-08,5.763084e-08,0.000000e+00
2020-04-03,1.156773e-06,0.000006,0.000000,0.000493,0.000000e+00,0.0,0.000021,0.000000,0.000031,0.000047,...,0.000064,1.775620e-08,0.000028,0.000088,0.000009,9.103212e-08,3.463780e-08,4.186711e-08,1.728925e-07,0.000000e+00
2020-04-04,0.000000e+00,0.000009,0.000003,0.000143,0.000000e+00,0.0,0.000062,0.000003,0.000025,0.000019,...,0.000067,0.000000e+00,0.000065,0.000099,0.000005,1.122730e-06,0.000000e+00,0.000000e+00,0.000000e+00,6.925679e-08
2020-04-05,9.415591e-07,0.000010,0.000007,0.000351,6.491449e-08,0.0,0.000000,0.000004,0.000012,0.000019,...,0.000056,0.000000e+00,0.000000,0.000105,0.000004,1.183418e-06,0.000000e+00,1.046678e-08,0.000000e+00,0.000000e+00

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-12,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-19,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-26,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,8.732968e-10,0.000000e+00,0.000000e+00,0.000000e+00,2.990508e-09,0.000000e+00,0.000000e+00
2020-02-02,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,4.297167e-09,0.000000e+00,0.000000,2.619891e-09,0.000000e+00,0.000000e+00,0.000000e+00,7.476269e-09,0.000000e+00,0.000000e+00
2020-02-09,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,4.297167e-09,0.000000e+00,0.000000,1.746594e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.046678e-08,0.000000e+00,0.000000e+00
2020-02-16,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,1.074292e-08,0.000000e+00,0.000000,1.309945e-09,0.000000e+00,0.000000e+00,0.000000e+00,2.990508e-09,0.000000e+00,0.000000e+00
2020-02-23,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,8.732968e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-03-01,3.843099e-09,0.000000,3.382961e-09,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,4.839701e-08,0.000000,...,3.008017e-08,0.000000e+00,0.000000,1.484605e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-03-08,1.152930e-08,0.000000,5.412738e-08,0.000002,0.000000e+00,0.0,0.000000,2.889603e-08,0.000000e+00,0.000000,...,3.931908e-07,0.000000e+00,0.000000,1.589400e-07,0.000000e+00,0.000000e+00,0.000000e+00,7.476269e-09,0.000000e+00,0.000000e+00
2020-03-15,2.305859e-08,0.000002,6.765923e-08,0.000002,0.000000e+00,0.0,0.000001,1.155841e-07,9.195433e-07,0.000003,...,2.006777e-06,0.000000e+00,0.000000,1.099481e-06,2.484977e-07,0.000000e+00,4.948257e-08,4.784812e-08,0.000000e+00,0.000000e+00
2020-03-22,5.380338e-08,0.000002,1.928288e-07,0.000160,9.273499e-09,0.0,0.000000,5.779205e-07,6.775582e-06,0.000003,...,8.332206e-06,1.521960e-08,0.000000,1.039049e-05,5.342700e-06,1.430505e-07,1.286547e-07,6.130541e-08,1.646595e-08,1.978765e-08
2020-03-29,3.151341e-07,0.000006,1.065633e-06,0.000408,9.273499e-09,0.0,0.000009,1.669548e-06,1.277681e-05,0.000032,...,2.593555e-05,1.775620e-08,0.000029,4.275574e-05,6.999352e-06,4.334863e-07,4.107053e-07,1.928877e-07,2.140574e-07,4.946913e-08
2020-04-05,6.302682e-07,0.000007,3.014219e-06,0.000293,2.782050e-08,0.0,0.000012,2.266733e-06,1.674537e-05,0.000049,...,5.331495e-05,2.029280e-08,0.000024,8.190302e-05,3.975963e-06,5.765368e-07,1.237064e-07,2.541932e-08,9.056274e-08,1.978765e-08

,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,Aruba,...,United Kingdom,United Republic of Tanzania,United States Virgin Islands,United States of America,Uruguay,Uzbekistan,Venezuela,Vietnam,Zambia,Zimbabwe
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-12,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-15,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-18,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-21,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,1.018846e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-24,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.977851e-09,0.000000e+00,0.000000e+00
2020-01-27,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,4.075385e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-01-30,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-02-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,1.002672e-08,0.000000e+00,0.000000,3.056539e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.744463e-08,0.000000e+00,0.000000e+00
2020-02-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,3.056539e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.046678e-08,0.000000e+00,0.000000e+00
2020-02-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,5.013361e-09,0.000000e+00,0.000000,1.018846e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.046678e-08,0.000000e+00,0.000000e+00
2020-02-11,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,2.506681e-08,0.000000e+00,0.000000,1.018846e-09,0.000000e+00,0.000000e+00,0.000000e+00,6.977851e-09,0.000000e+00,0.000000e+00
2020-02-14,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,5.013361e-09,0.000000e+00,0.000000,2.037693e-09,0.000000e+00,0.000000e+00,0.000000e+00,3.488926e-09,0.000000e+00,0.000000e+00
2020-02-17,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-02-20,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-02-23,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,0.000000e+00,0.000000e+00,0.000000,2.037693e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-02-26,8.967230e-09,0.000000e+00,7.893576e-09,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,2.005345e-08,0.000000e+00,0.000000,1.833923e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-02-29,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,0.000000e+00,0.000000e+00,0.000000,...,2.506681e-08,0.000000e+00,0.000000,1.324500e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-03-03,0.000000e+00,0.000000e+00,1.578715e-08,0.000004,0.000000e+00,0.0,0.000000,0.000000e+00,1.129264e-07,0.000000,...,1.102939e-07,0.000000e+00,0.000000,3.769731e-08,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-03-06,0.000000e+00,0.000000e+00,1.105101e-07,0.000000,0.000000e+00,0.0,0.000000,1.498312e-08,0.000000e+00,0.000000,...,3.760021e-07,0.000000e+00,0.000000,1.324500e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2020-03-09,2.690169e-08,2.325817e-07,2.368073e-08,0.000000,0.000000e+00,0.0,0.000000,7.491562e-08,0.000000e+00,0.000000,...,7.921111e-07,0.000000e+00,0.000000,3.270497e-07,0.000000e+00,0.000000e+00,0.000000e+00,4.884496e-08,0.000000e+00,0.000000e+00
2020-03-12,2.690169e-08,1.046618e-06,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000,5.244094e-08,3.387791e-07,0.000000,...,9.174451e-07,0.000000e+00,0.000000,7.722855e-07,0.000000e+00,0.000000e+00,0.000000e+00,3.140033e-08,0.000000e+00,0.000000e+00
2020-03-15,2.690169e-08,3.139853e-06,1.341908e-07,0.000004,0.000000e+00,0.0,0.000003,1.947806e-07,1.806822e-06,0.000006,...,3.429139e-06,0.000000e+00,0.000000,1.669889e-06,5.798280e-07,0.000000e+00,1.154593e-07,4.884496e-08,0.000000e+00,0.000000e+00
2020-03-18,1.076068e-07,1.976945e-06,1.815523e-07,0.000052,0.000000e+00,0.0,0.000000,2.547131e-07,6.549729e-06,0.000000,...,4.060823e-06,5.918734e-09,0.000000,3.541510e-06,4.252072e-06,1.618349e-07,2.655565e-07,2.791141e-08,0.000000e+00,0.000000e+00
2020-03-21,1.793446e-08,1.744363e-06,2.683816e-07,0.000264,0.000000e+00,0.0,0.000000,5.918334e-07,6.549729e-06,0.000006,...,1.019216e-05,1.183747e-08,0.000000,1.344571e-05,5.798280e-06,1.719496e-07,3.463780e-08,9.071207e-08,3.842056e-08,2.308560e-08
2020-03-24,1.434757e-07,3.488726e-06,7.498898e-07,0.000251,2.163816e-08,0.0,0.000000,1.071293e-06,6.549729e-06,0.000025,...,1.337063e-05,5.326861e-08,0.000053,2.732342e-05,5.025176e-06,1.618349e-07,5.542048e-07,1.256013e-07,1.921028e-08,2.308560e-08
2020-03-27,3.138530e-07,8.605524e-06,9.156549e-07,0.000394,1.081908e-08,0.0,0.000021,2.157570e-06,1.524506e-05,0.000050,...,2.510691e-05,5.918734e-09,0.000000,4.029435e-05,7.344487e-06,3.438991e-07,2.655565e-07,1.046678e-07,2.113131e-07,2.308560e-08
2020-03-30,3.497220e-07,4.419053e-06,1.176143e-06,0.000476,4.327633e-08,0.0,0.000000,1.730551e-06,1.072800e-05,0.000069,...,3.942507e-05,5.918734e-09,0.000041,5.810888e-05,6.861298e-06,6.271102e-07,1.385512e-07,2.616694e-07,2.881542e-07,9.234238e-08
2020-04-02,6.994439e-07,5.465670e-06,3.102176e-06,0.000242,1.081908e-08,0.0,0.000000,2.344859e-06,1.660018e-05,0.000016,...,4.989297e-05,3.551241e-08,0.000000,7.508490e-05,2.802502e-06,4.248166e-07,2.771024e-07,2.442248e-08,1.344719e-07,2.308560e-08
2020-04-05,6.994439e-07,8.605524e-06,3.575790e-06,0.000329,2.163816e-08,0.0,0.000028,2.382317e-06,2.247235e-05,0.000028,...,6.231107e-05,5.918734e-09,0.000031,9.731612e-05,5.991556e-06,7.990597e-07,1.154593e-08,1.744463e-08,5.763084e-08,2.308560e-08

## Global data

Lastly we will create one dataset that contains all the different metrics for the global population.

In [9]:
global_pop = df_populations.sum(axis=0).values
dict_global = {'Date': dates_all}

sr_cases_3days = df_cases_3days.sum(axis=1)
sr_deahs_3days = df_deaths_3days.sum(axis=1)

sr_cases_weekly = df_cases_weekly.sum(axis=1)
sr_deaths_weekly = df_deaths_weekly.sum(axis=1)

cases_3days = []
deaths_3days = []
cases_weekly = []
deaths_weekly = []
for date in dates_all:
    if date in dates_3days:
        cases_3days.append(sr_cases_3days[date])
        deaths_3days.append(sr_deahs_3days[date])
    else: 
        cases_3days.append(0)
        deaths_3days.append(0)
        
    if date in dates_weekly:
        cases_weekly.append(sr_cases_weekly[date])
        deaths_weekly.append(sr_deaths_weekly[date])
    else: 
        cases_weekly.append(0)
        deaths_weekly.append(0)

In [10]:
dict_global['cases_daily'] = df_cases_daily.sum(axis=1).values
dict_global['cases_3days'] = cases_3days
dict_global['cases_weekly'] = cases_weekly
dict_global['cases_total'] = df_cases_total.sum(axis=1).values

dict_global['incidence_daily'] = df_cases_daily.sum(axis=1).values / global_pop
dict_global['incidence_3days'] = cases_3days / global_pop
dict_global['incidence_weekly'] = cases_weekly / global_pop
dict_global['prevalence'] = df_cases_total.sum(axis=1).values / global_pop

dict_global['deaths_daily']  = df_deaths_daily.sum(axis=1).values
dict_global['deaths_w3days'] = deaths_3days
dict_global['deaths_weekly'] = deaths_weekly
dict_global['deaths_total']  = df_deaths_total.sum(axis=1).values
dict_global['mortality']  = (df_deaths_total.sum(axis=1) / df_cases_total.sum(axis=1)).values

In [11]:
df_global = pd.DataFrame(dict_global).set_index('Date')
display(df_global)
df_global.to_csv('../data/global.csv')

,cases_daily,cases_3days,cases_weekly,cases_total,incidence_daily,incidence_3days,incidence_weekly,prevalence,deaths_daily,deaths_w3days,deaths_weekly,deaths_total,mortality
Date,,,,,,,,,,,,,
2019-12-31,27,0.000000,0.000000,27,3.600777e-09,0.000000,0.00000,3.600777e-09,0,0.000000,0.000000,0,0.000000
2020-01-01,0,0.000000,0.000000,27,0.000000e+00,0.000000,0.00000,3.600777e-09,0,0.000000,0.000000,0,0.000000
2020-01-02,0,0.000000,0.000000,27,0.000000e+00,0.000000,0.00000,3.600777e-09,0,0.000000,0.000000,0,0.000000
2020-01-03,17,0.000000,0.000000,44,2.267156e-09,0.000000,0.00000,5.867933e-09,0,0.000000,0.000000,0,0.000000
2020-01-04,0,0.000000,0.000000,44,0.000000e+00,0.000000,0.00000,5.867933e-09,0,0.000000,0.000000,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,73512,0.000000,0.000000,851308,9.803716e-06,0.000000,0.00000,1.135322e-04,4614,0.000000,0.000000,41885,0.049201
2020-04-02,77128,71027.666667,0.000000,928436,1.028595e-05,0.000009,0.00000,1.238182e-04,4998,4436.333333,0.000000,46883,0.050497
2020-04-03,71813,0.000000,0.000000,1000249,9.577133e-06,0.000000,0.00000,1.333953e-04,4631,0.000000,0.000000,51514,0.051501
2020-04-04,81805,0.000000,0.000000,1082054,1.090969e-05,0.000000,0.00000,1.443050e-04,6627,0.000000,0.000000,58141,0.053732
2020-04-05,92598,82072.000000,73969.428571,1174652,1.234906e-05,0.000011,0.00001,1.566541e-04,6259,5839.000000,4850.142857,64400,0.054825

## Continental data

In [12]:
continents = ['africa', 'asia', 'europe', 'north_america', 'oceania', 'south_america']

africa = ['Malawi', 'Niger', 'Nigeria', 'Zimbabwe','Zambia','United Republic of Tanzania','Uganda','Tunisia','Togo','Sudan','South Africa','Somalia','Sierra Leone','Seychelles', 'Senegal','Rwanda', 'Namibia','Mozambique','Morocco','Mauritius','Mauritania','Mali','Madagascar','Libya','Liberia', 'Kenya','Guinea Bissau','Guinea', 'Ghana', 'Gambia', 'Gabon','Ethiopia', 'Eswatini','Eritrea','Equatorial Guinea','Egypt', 'Djibouti', 'Democratic Republic of the Congo','Cote dIvoire', 'Congo', 'Chad', 'Central African Republic', 'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cameroon', 'Cape Verde']
asia = ['Cases on an international conveyance Japan', 'Vietnam','Uzbekistan', 'United Arab Emirates','Turkey','Timor Leste','Thailand','Taiwan','Syria','Sri Lanka','South Korea','Singapore','Saudi Arabia','Qatar', 'Philippines','Palestine','Pakistan','Oman', 'Nepal','Myanmar', 'Mongolia','Maldives','Malaysia','Lebanon','Laos','Kyrgyzstan', 'Kuwait','Jordan', 'Japan', 'Israel','Iraq','Iran','Indonesia','India','China', 'Afghanistan', 'Armenia', 'Bahrain', 'Bangladesh', 'Bhutan', 'Brunei Darussalam', 'Cambodia']
europe = ['United Kingdom','Ukraine','Switzerland','Sweden','Spain','Slovenia','Slovakia','Serbia','San Marino','Romania', 'Russia','Portugal','Poland','Norway', 'North Macedonia','Netherlands','Monaco','Montenegro','Moldova','Malta','Luxembourg', 'Lithuania','Liechtenstein','Latvia','Kosovo','Kazakhstan', 'Jersey','Italy', 'Isle of Man','Ireland','Azerbaijan','Georgia','Iceland', 'Hungary', 'Holy See','Guernsey', 'Greece', 'Gibraltar', 'Germany', 'France', 'Finland', 'Faroe Islands', 'Estonia','Denmark','Czech Republic', 'Cyprus', 'Croatia', 'Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria']
north_america = ['Belize', 'United States of America','United States Virgin Islands','Turks and Caicos islands','Sint Maarten','Saint Vincent and the Grenadines','Saint Lucia','Saint Kitts and Nevis','Saint Barthelemy','Puerto Rico', 'Panama','Nicaragua', 'Montserrat','Mexico', 'Jamaica', 'Honduras', 'Haiti', 'Guatemala', 'Grenada', 'Greenland','El Salvador','Dominican Republic', 'Dominica', 'Cuba', 'Cayman Islands', 'Anguilla', 'Antigua and Barbuda', 'Bahamas', 'Barbados', 'Bermuda', 'British Virgin Islands', 'Canada']
oceania = ['Papua New Guinea','Northern Mariana Islands','New Zealand','New Caledonia','Guam','French Polynesia', 'Fiji','Australia']
south_america = ['Falkland Islands (Malvinas)', 'Bonaire, Saint Eustatius and Saba', 'Venezuela','Uruguay','Trinidad and Tobago','Suriname','Peru','Paraguay', 'Guyana', 'Ecuador', 'CuraÃ§ao', 'Costa Rica', 'Colombia', 'Chile', 'Argentina', 'Aruba', 'Bolivia', 'Brazil']


africa.sort()
asia.sort()
europe.sort()
north_america.sort()
south_america.sort()
oceania.sort()

missing = []
for country in countries_all:
    if country not in africa and country not in asia and country not in europe and country not in north_america and country not in south_america and country not in oceania:
        missing.append(country)
            
to_much = []
for continent in continents:
    for country in eval(continent):
        if country not in countries_all:
            to_much.append(country)
            
if missing != [] or to_much != []:
    print(f'The follwoing countries are missing: {missing}')
    print(f'The follwoing countries are to much: {to_much}')

In [13]:
for continent in continents:
    continent_pop = df_populations.loc[eval(continent)].sum(axis=0).values
    
    sr_cases_3days = df_cases_3days[eval(continent)].sum(axis=1)
    sr_deahs_3days = df_deaths_3days[eval(continent)].sum(axis=1)

    sr_cases_weekly = df_cases_weekly[eval(continent)].sum(axis=1)
    sr_deaths_weekly = df_deaths_weekly[eval(continent)].sum(axis=1)

    cases_3days = []
    deaths_3days = []
    cases_weekly = []
    deaths_weekly = []
    for date in dates_all:
        if date in dates_3days:
            cases_3days.append(sr_cases_3days[date])
            deaths_3days.append(sr_deahs_3days[date])
        else: 
            cases_3days.append(0)
            deaths_3days.append(0)

        if date in dates_weekly:
            cases_weekly.append(sr_cases_weekly[date])
            deaths_weekly.append(sr_deaths_weekly[date])
        else: 
            cases_weekly.append(0)
            deaths_weekly.append(0)

    dict_coninent = {'Date': dates_all}

    dict_coninent['cases_daily'] = df_cases_daily[eval(continent)].sum(axis=1).values
    dict_coninent['cases_3days'] = cases_3days
    dict_coninent['cases_weekly'] = cases_weekly
    dict_coninent['cases_total'] = df_cases_total[eval(continent)].sum(axis=1).values

    dict_coninent['prevalence'] = df_cases_total[eval(continent)].sum(axis=1).values / continent_pop
    dict_coninent['incidence_daily'] = df_cases_daily[eval(continent)].sum(axis=1).values / continent_pop
    dict_coninent['incidence_3days'] = cases_3days / continent_pop
    dict_coninent['incidence_weekly'] = cases_weekly / global_pop

    dict_coninent['deaths_daily']  = df_deaths_daily[eval(continent)].sum(axis=1).values
    dict_coninent['deaths_3days'] = deaths_3days
    dict_coninent['deaths_weekly'] = deaths_weekly
    dict_coninent['deaths_total']  = df_deaths_total[eval(continent)].sum(axis=1).values
    dict_coninent['mortality']  = (df_deaths_total[eval(continent)].sum(axis=1) / df_cases_total[eval(continent)].sum(axis=1)).values
    
    print(continent)
    df_continent = pd.DataFrame(dict_coninent).set_index('Date')
    display(df_continent)
    df_continent.to_csv('../data/' + continent + '.csv')

africa

,cases_daily,cases_3days,cases_weekly,cases_total,prevalence,incidence_daily,incidence_3days,incidence_weekly,deaths_daily,deaths_3days,deaths_weekly,deaths_total,mortality
Date,,,,,,,,,,,,,
2019-12-31,0,0.000000,0.0,0,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-01,0,0.000000,0.0,0,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-02,0,0.000000,0.0,0,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-03,0,0.000000,0.0,0,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-04,0,0.000000,0.0,0,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0,0.000000,0.000000,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,430,0.000000,0.0,5494,0.000004,3.421276e-07,0.000000e+00,0.000000e+00,18,0.000000,0.000000,180,0.032763
2020-04-02,754,558.666667,0.0,6248,0.000005,5.999168e-07,4.445007e-07,0.000000e+00,44,27.666667,0.000000,224,0.035851
2020-04-03,496,0.000000,0.0,6744,0.000005,3.946402e-07,0.000000e+00,0.000000e+00,27,0.000000,0.000000,251,0.037218
2020-04-04,579,0.000000,0.0,7323,0.000006,4.606788e-07,0.000000e+00,0.000000e+00,32,0.000000,0.000000,283,0.038645
2020-04-05,1166,747.000000,630.0,8489,0.000007,9.277228e-07,5.943473e-07,8.401813e-08,96,51.666667,36.857143,379,0.044646

asia

,cases_daily,cases_3days,cases_weekly,cases_total,prevalence,incidence_daily,incidence_3days,incidence_weekly,deaths_daily,deaths_3days,deaths_weekly,deaths_total,mortality
Date,,,,,,,,,,,,,
2019-12-31,27,0.0,0.000000,27,6.114138e-09,6.114138e-09,0.000000,0.000000,0,0.000000,0.000000,0,0.000000
2020-01-01,0,0.0,0.000000,27,6.114138e-09,0.000000e+00,0.000000,0.000000,0,0.000000,0.000000,0,0.000000
2020-01-02,0,0.0,0.000000,27,6.114138e-09,0.000000e+00,0.000000,0.000000,0,0.000000,0.000000,0,0.000000
2020-01-03,17,0.0,0.000000,44,9.963781e-09,3.849643e-09,0.000000,0.000000,0,0.000000,0.000000,0,0.000000
2020-01-04,0,0.0,0.000000,44,9.963781e-09,0.000000e+00,0.000000,0.000000,0,0.000000,0.000000,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,6887,0.0,0.000000,177605,4.021857e-05,1.559558e-06,0.000000,0.000000,228,0.000000,0.000000,7119,0.040083
2020-04-02,8480,7854.0,0.000000,186085,4.213887e-05,1.920292e-06,0.000002,0.000000,283,243.333333,0.000000,7402,0.039778
2020-04-03,8791,0.0,0.000000,194876,4.412958e-05,1.990718e-06,0.000000,0.000000,294,0.000000,0.000000,7696,0.039492
2020-04-04,6157,0.0,0.000000,201033,4.552383e-05,1.394250e-06,0.000000,0.000000,150,0.000000,0.000000,7846,0.039028
2020-04-05,12244,9064.0,8252.142857,213277,4.829648e-05,2.772648e-06,0.000002,0.000001,444,296.000000,259.571429,8290,0.038870

europe

,cases_daily,cases_3days,cases_weekly,cases_total,prevalence,incidence_daily,incidence_3days,incidence_weekly,deaths_daily,deaths_3days,deaths_weekly,deaths_total,mortality
Date,,,,,,,,,,,,,
2019-12-31,0,0.000000,0.0,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-01,0,0.000000,0.0,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-02,0,0.000000,0.0,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-03,0,0.000000,0.0,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-04,0,0.000000,0.0,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,37307,0.000000,0.0,445256,0.000571,0.000048,0.000000,0.000000,3354,0.000000,0.000000,29864,0.067072
2020-04-02,36208,34167.000000,0.0,481464,0.000617,0.000046,0.000044,0.000000,3453,3168.666667,0.000000,33317,0.069199
2020-04-03,29264,0.000000,0.0,510728,0.000655,0.000038,0.000000,0.000000,3276,0.000000,0.000000,36593,0.071649
2020-04-04,38027,0.000000,0.0,548755,0.000704,0.000049,0.000000,0.000000,5137,0.000000,0.000000,41730,0.076045
2020-04-05,40515,35935.333333,34306.0,589270,0.000756,0.000052,0.000046,0.000005,4149,4187.333333,3511.857143,45879,0.077857

north_america

,cases_daily,cases_3days,cases_weekly,cases_total,prevalence,incidence_daily,incidence_3days,incidence_weekly,deaths_daily,deaths_3days,deaths_weekly,deaths_total,mortality
Date,,,,,,,,,,,,,
2019-12-31,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-01,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-02,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-03,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
2020-01-04,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,26676,0.000000,0.000000,202592,0.000352,0.000046,0.000000,0.000000,938,0.000000,0.000000,4314,0.021294
2020-04-02,28824,26197.333333,0.000000,231416,0.000402,0.000050,0.000046,0.000000,1100,915.333333,0.000000,5414,0.023395
2020-04-03,30836,0.000000,0.000000,262252,0.000456,0.000054,0.000000,0.000000,955,0.000000,0.000000,6369,0.024286
2020-04-04,34476,0.000000,0.000000,296728,0.000515,0.000060,0.000000,0.000000,1194,0.000000,0.000000,7563,0.025488
2020-04-05,36195,33835.666667,28546.714286,332923,0.000578,0.000063,0.000059,0.000004,1433,1194.000000,953.142857,8996,0.027021

oceania

,cases_daily,cases_3days,cases_weekly,cases_total,prevalence,incidence_daily,incidence_3days,incidence_weekly,deaths_daily,deaths_3days,deaths_weekly,deaths_total,mortality
Date,,,,,,,,,,,,,
2019-12-31,0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-01,0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-02,0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-03,0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-04,0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,164,0.0,0.000000,5488,0.000137,0.000004,0.000000,0.000000e+00,3,0.000000,0.000000,24,0.004373
2020-04-02,355,362.0,0.000000,5843,0.000146,0.000009,0.000009,0.000000e+00,2,2.666667,0.000000,26,0.004450
2020-04-03,304,0.0,0.000000,6147,0.000153,0.000008,0.000000,0.000000e+00,2,0.000000,0.000000,28,0.004555
2020-04-04,390,0.0,0.000000,6537,0.000163,0.000010,0.000000,0.000000e+00,8,0.000000,0.000000,36,0.005507
2020-04-05,194,296.0,333.714286,6731,0.000168,0.000005,0.000007,4.450484e-08,4,4.666667,3.428571,40,0.005943

south_america

,cases_daily,cases_3days,cases_weekly,cases_total,prevalence,incidence_daily,incidence_3days,incidence_weekly,deaths_daily,deaths_3days,deaths_weekly,deaths_total,mortality
Date,,,,,,,,,,,,,
2019-12-31,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-01,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-02,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-03,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
2020-01-04,0,0.000000,0.000000,0,0.000000,0.000000,0.000000,0.000000e+00,0,0.000000,0.000000,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-01,2048,0.000000,0.000000,14873,0.000035,0.000005,0.000000,0.000000e+00,73,0.000000,0.000000,384,0.025819
2020-04-02,2507,1888.666667,0.000000,17380,0.000040,0.000006,0.000004,0.000000e+00,116,78.666667,0.000000,500,0.028769
2020-04-03,2122,0.000000,0.000000,19502,0.000045,0.000005,0.000000,0.000000e+00,77,0.000000,0.000000,577,0.029587
2020-04-04,2176,0.000000,0.000000,21678,0.000050,0.000005,0.000000,0.000000e+00,106,0.000000,0.000000,683,0.031507
2020-04-05,2284,2194.000000,1900.857143,23962,0.000056,0.000005,0.000005,2.535023e-07,133,105.333333,85.285714,816,0.034054